
package trader;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "StockPrice", targetNamespace = "http://web.tarder/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StockPrice {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStockPrice", targetNamespace = "http://web.tarder/", className = "trader.GetStockPrice")
    @ResponseWrapper(localName = "getStockPriceResponse", targetNamespace = "http://web.tarder/", className = "trader.GetStockPriceResponse")
    public String getStockPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
