
package trader;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StockPriceService", targetNamespace = "http://web.tarder/", wsdlLocation = "http://localhost:8080/BrokerTool/StockPriceService?WSDL")
public class StockPriceService
    extends Service
{

    private final static URL STOCKPRICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(trader.StockPriceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = trader.StockPriceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/BrokerTool/StockPriceService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/BrokerTool/StockPriceService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        STOCKPRICESERVICE_WSDL_LOCATION = url;
    }

    public StockPriceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockPriceService() {
        super(STOCKPRICESERVICE_WSDL_LOCATION, new QName("http://web.tarder/", "StockPriceService"));
    }

    /**
     * 
     * @return
     *     returns StockPrice
     */
    @WebEndpoint(name = "StockPricePort")
    public StockPrice getStockPricePort() {
        return super.getPort(new QName("http://web.tarder/", "StockPricePort"), StockPrice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockPrice
     */
    @WebEndpoint(name = "StockPricePort")
    public StockPrice getStockPricePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.tarder/", "StockPricePort"), StockPrice.class, features);
    }

}
